In [2]:
import numpy as np
a=np.array([20,40,50,70,10])
b=np.array([6,2,9,7,1])
print(a)
print(b)
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[20 40 50 70 10]
[6 2 9 7 1]
[26 42 59 77 11]
[14 38 41 63  9]
[120  80 450 490  10]
[ 3.33333333 20.          5.55555556 10.         10.        ]


In [13]:
import numpy as np
a=np.array([20,40,50,70,10])
b=np.array([6,2,9,7,1])
print(a.dot(b))
set = 3
print("scalar values=",set)
print("array:",a)
print("result:",a*set)

1150
scalar values= 3
array: [20 40 50 70 10]
result: [ 60 120 150 210  30]


In [7]:
import numpy as np
a=np.array([[10,20],[30,40]])
b=np.array([[3,7],[5,9]])
print(a%b)

[[1 6]
 [0 4]]


In [15]:
def mf(x,y):
    if x>y:
        return x-y
    else:
        return x+y 
  
a =[10,7,2]
b =[6,5,3]
vfunc=np.vectorize(mf)
print("array1",a)
print("array2",b)
print("result",vfunc(a,b))

array1 [10, 7, 2]
array2 [6, 5, 3]
result [4 2 5]
