In [9]:
#index retrieval
import numpy as np
a=np.array([1,6,2,7,6,4])
x=np.where(a==6)
print(x)

(array([1, 4], dtype=int64),)


In [16]:
#position by sorting
a=np.array([0,1,2,2,7,8,9])
x=np.searchsorted(a,3,side='left')
print(x)

4


In [17]:
#array sorting
a=np.array([9,5,2,7,6,4])
b=np.array([[7,4,9],[9,1,4]])
print(np.sort(a))
print(np.sort(b))

[2 4 5 6 7 9]
[[4 7 9]
 [1 4 9]]


In [18]:
#boolean indexing 1
a=np.array([31,78,69,88])
x=[False,True, False, True]
new=a[x]
print(x)
print(new)

[False, True, False, True]
[78 88]


In [20]:
#boolean indexing 2
a=np.array([31,78,69,88])
filter=a<70
new=a[filter]
print(filter)
print(new)

[ True False  True False]
[31 69]
