In [2]:
#1-D array
import numpy as np
a=np.array([10,20,30,40,50])
print("One dimensional array:",a)

One dimensional array: [10 20 30 40 50]


In [4]:
#2-D array
import numpy as np
b=np.array([[10,20,30,40,50],[60,70,80,90,100]])
print("Two dimensional array:",b)

Two dimensional array: [[ 10  20  30  40  50]
 [ 60  70  80  90 100]]


In [5]:
#array of zeros
import numpy as np
c=np.zeros((3,5))
print("\n Array with all zeros:\n",c)


 Array with all zeros:
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [6]:
#random value
import numpy as np
d=np.random.random((3,3))
print("\n Random value:\n",d)


 Random value:
 [[0.35507195 0.81209456 0.8294121 ]
 [0.77540669 0.63444027 0.34330152]
 [0.32895178 0.86875831 0.01788786]]


In [8]:
#range of values
import numpy  as np
e=np.arange(0,100,5)
print("\n Range value:\n",e)


 Range value:
 [ 0  5 10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]


In [9]:
#reshaping array
arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
newarr=arr.reshape((4,3))
print("\n Original array:\n",arr)
print("\n Reshaped array [4,3]:\n", newarr)


 Original array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

 Reshaped array [4,3]:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [11]:
#merging all array
import numpy as np
a=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15]])
print("flattened array:\n",flat)

flattened array:
 [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [9]:
#dimension of array
import numpy as np
a=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15]])
print("\n no. of dimensions:", a.ndim)


 no. of dimensions: 2


In [1]:
#shape of array
import numpy as np
a=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15]])
print("\n shape of array:",a.shape)


 shape of array: (5, 3)


In [4]:
#array element type
import numpy as np
a=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15]])
print("\n Array element type:", a.dtype)


 Array element type: int32


In [7]:
#convert int to float
import numpy as np
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
newtype=a.astype('f')
print("\nConvert array element:\n",newtype)
print("Array type:",newtype.dtype)


Convert array element:
 [[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
Array type: float32


In [19]:
#No. of elements
import numpy as np
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print("\n Array size:", a.size)


 Array size: 9


In [20]:
#length of array
import numpy as np
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print("\n Array size:", len(a))


 Array size: 3


In [22]:
#all functions
import numpy as np
a=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15]])
b=np.zeros((5,3))
c=np.random.random((5,3))
d=np.arange(0,50,2)
e=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15]])
newe=e.reshape((3,5))
flat=a.flatten()
print("\n array:\n",a)
print("\n array with all zeros:\n",b)
print("\n array with random values:\n",c)
print("\n range value:\n",d)
print("\n original array:\n",e)
print("\n reshaped array[3,5]:\n",newe)
print("flattened array:\n",flat)
print("\n no. of dimensions:", a.ndim)
print("\n shape of array:",a.shape)
print("\n Array element type:", a.dtype)
newtype=a.astype('f')
print("\nConvert array element:\n",newtype)
print("Array type:",newtype.dtype)
print("\n Array size:", a.size)
print("\n No. of elements:", len(a))


 array:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]

 array with all zeros:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

 array with random values:
 [[0.67831523 0.97120666 0.16592046]
 [0.69751729 0.76927021 0.34644833]
 [0.12867062 0.90872501 0.30933082]
 [0.23184043 0.9371988  0.5391175 ]
 [0.93597302 0.4794936  0.48030169]]

 range value:
 [ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46
 48]

 original array:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]

 reshaped array[3,5]:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
flattened array:
 [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]

 no. of dimensions: 2

 shape of array: (5, 3)

 Array element type: int32

Convert array element:
 [[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]
 [13. 14. 15.]]
Array type: float32

 Array size: 15

 No. of elements: 5
